#!/bin/sh

object=$1 && shift
method=$1 && shift

test "$method" == "_default-example" && {
    echo this is an example of a default method handler
    echo this code is at $0
    exit 0
    }

echo $object.$method not found
