#!/bin/sh
ob=$1 && shift

if [ -z $NOCD ]; then
    cd $TOB_path
    target="$*"
else
    target="$TOB_path/$*"
fi
for prop in $target; do
    if [ -e $prop ]; then
        test $VERBOSE &&
             echo $prop:
        /bin/cat $prop
    else
        echo ERROR: no property $prop
        exit 1
    fi
done
exit 0
