#!/usr/bin/env bash
echo $0 is deprecated, do not use 1>&2
exit 1

#!/usr/bin/perl -w
use strict;
use ThinObject;
my $prop = shift;
my $index1 = shift; # 1-based index into property
my $ob = ThinObject->new('.');
if ( defined $prop ) {
    my @value = $ob->get_property($prop);
    exit unless @value;
    if ( defined $index1 ) {
        print $value[$index1 - 1], "\n";
        }
    else {
        print "$_\n" foreach @value;
        }
    }
else {
    foreach $prop ( $ob->get_property() ) {
        print "$prop\n";
        }
    }
