#!/usr/bin/env bash

function usage () {
    printf "SYNOPSIS: ob.method [-v|--verbose|-V|--no-verbose|-h|--help] [method]\n"
    }

## if argument is specified, output only that method's full pathname

while test -n "$1"; do
    if test $1 == -v || test $1 == --verbose; then
        VERBOSE=1   
    elif test $1 == -V || test $1 == --no-verbose; then
        unset VERBOSE   
    elif test $1 == -q || test $1 == --quiet; then
        QUIET=1
        unset VERBOSE
    elif test $1 == -h; then
        usage
        exit 0
    elif test $1 == --help; then
        awk '/^NAME$/{ok=1}ok' $0
        exit 0
    elif test ${1#-} != $1; then
        echo unknown option: $1 >&2
        exit 1
    else
        METHOD=$1
    fi
    shift
done

for class in ${TOB_method_paths//:/ }; do
  # echo "looking in $class..."
    for f in $class/*; do
        test -d $f && continue
        test -f $f && test -x $f && {
            m=${f##*/} # strip path from method name
            echo $m $f
            }
    done
done |
    awk -v method="$METHOD" -v verbose="$VERBOSE" -v quiet="$QUIET" '
        {
        name = $1
        path = $2
        while ( m[name] ) {
            name = "super." name
            }
        m[name] = 1
        if ( method == name ) {
            if ( ! quiet ) {
                print path
                }
            found_method = 1
            }
        else if ( method == "" ) {
            if ( verbose ) {
                if ( ! quiet ) print name, path
                }
            else {
                if ( ! quiet ) print name
                }
            }
        } 
        END {
        if ( method == "" || found_method )
            exit 0
        if ( ! quiet )
            printf("method %s not found\n", method)
        exit(1)
        }
        '

exit $?

NAME
    method

SYNOPSIS
    ob.method [-v|--verbose|-V|--no-verbose] [-h|--help] [-q|--quiet] [method]
    
DESCRIPTION
    With no arguments, print all methods available to given object.  If a method
    name is specified, print its full pathname if found, otherwise exit with status
    1.

OPTIONS
    -v
    --verbose
    output full pathname for all methods (if method name not specified)

    -V
    --no-verbose
    output only method names

    -q
    --quiet
    suppress any output to stdout; exit status can be used to test if a method
    is found (value 0) or not (value 1)

    -h
    print a short synopsis

    --help
    print this manpage

AUTHOR
    ken.irving.ak@gmail.com (c) 2009

