#!/bin/sh
ob=$1 && shift

if test -z "$1"; then
    target="%"
else
    target="$*"
fi

if [ -z $NOCD ]; then
    cd $tob_path
else
    for f in $*; do
        ## non-option argument is the file/dir name to mkdir:
        if test $f == ${f#-}; then
            target="$target $tob_path/$f"
        else
            target="$target $f"
        fi
    done
fi
test $VERBOSE &&
    echo mkdir $target
/bin/mkdir $target
exit 0
