#!/bin/sh
ob=$1 && shift

tag="$1" && shift
value="$1" && shift
cd $tob_path
test -z "$tag" && { # list all parameters
    for f in *\=*; do echo $f; done
    exit 0
    }
test -n "$value" && { # set parameter value
    test -e $tag\=* && /bin/rm $tag\=* 
    /usr/bin/touch $tag\=$value
    }
## ASSERT: $tag is defined -- but may or may not exist
test ! -e $tag\=* && exit 1
exec /bin/ls $tag\=*
