#!/bin/sh

test -n "$1" || echo $TOB_object/

# list the path to any arguments found in the object:
for arg in $*; do
  # test -e $arg ||
  #     echo $arg not found >&2
    test -e $arg ||
        test -L $arg ||
            echo $TOB_object/$arg not found >&2
    echo $TOB_object/$arg
done

