#!/bin/sh
ob=$1 && shift

prop=$1 && shift

test ${prop:0:1} == - && {
    opt=$prop
    prop=$1 && shift
    if test $opt == --create-ok -o $opt == -c; then
        OK2CREATE=1
    elif test $opt == --no-create-ok -o $opt == -C; then
        unset OK2CREATE
    elif test $opt == --help; then
        awk '/^NAME/,/^END/' $0
        exit
    elif test $opt == -h; then
        echo "SYNOPSIS: Object.set [OPTIONS] PROPERTY [ARGUMENTS]"
        exit
    else
        echo Object.set: unknown option $opt
        exit 1
    fi
    }

test -e $TOB_object_path/$prop || {
    test -n "$OK2CREATE" || {
        echo ERROR: no property $prop
        exit 1
        }
    }

test -n "$1" &&
    exec /bin/echo $* > $TOB_object_path/$prop

exec /bin/cat > $TOB_object_path/$prop


NAME
    Object.set

SYNOPSIS
    Object.set [OPTIONS] PROPERTY [ARGUMENTS]"

OPTIONS
    --create-ok
    -c
    method will create the named property if it does not exist

    --no-create-ok
    -C
    method will fail if the named property does not exist

    --help
    print this manpage

    -h
    print a synopsis

VARIABLES
    OK2CREATE
    set or cleared by --create-ok or --no-create-ok, but can also be
    defined/exported in the environment

DESCRIPTION
    If arguments are present, they are copied into the named property
    file.

    If no arguments are given, standard input is copied into the named
    property

BUGS
    Whitespace in argument list is not preserved.

AUTHOR
    Ken Irving <fnkci@uaf.edu> 2008
