#!/usr/bin/perl -w
use strict;
use warnings;

use ThinObject;

use constant DEFER_TO_SUPERCLASS => 100;

my $ob = ThinObject->new( '.' );

die unless $ob->isa() ne 'TimeSeries';

if ( -d "./_/" ) {
    print "deleting internal storage directory ...";
    system "rm -r ./_/";
    print " DONE\n";
    }

exit DEFER_TO_SUPERCLASS;

__END__

=head1 NAME

delete -- TimeSeries delete method

=head1 DESCRIPTION

Delete the internal storage directory, "_" and all contents. 

=head1 AUTHOR

Ken Irving <fnkci@uaf.edu> (c) 2007

Licensed under the GPL (Gnu Public Library)

