#!/usr/bin/perl -w
use strict;
use warnings;

use Getopt::Long;
my $object = shift;

my $pad = 5;

## process commandline options:
use Getopt::Long;
GetOptions (
    'h'             => sub { print "see --help\n"; exit 1 },
    'help'          => sub { exec "pod2text $0" },
    'pad=i'  => \$pad,
    ) or die "$!\n";

my $input = shift;

if ( $pad > 0 ) {
    printf "%0${pad}s\n", encode($input);
    }
else {
    print encode($input), "\n";
    }

exec "$0 dummy --pad $pad @ARGV" if @ARGV;

exit;

sub encode { # encode number into base-32 character string
    my $n = shift;
    my $b32 = '';
    my @code = ( 0..9, 'a'..'h', 'j', 'k', 'm', 'n', 'p'..'t', 'v'..'z'); 
    while ( $n > 0 ) {
        $b32 = $code[ $n % 32 ] . $b32;
        $n = int( $n / 32 );
        }
    return $b32;
    }

=head1 NAME

TimeSeries.encode32 -- encode numbers to base-32 character string

=head1 SYNOPSIS

  timeseries.encode32 [--pad N] NUMBER ...

=head1 DESCRIPTION

Encode numeric value in special base-32 character string, zero-padded to
five characters by default.

=head1 OPTIONS

=over

=item --help

=item --pad

0-pad result to PAD characters, default is --pad 5

=head1 BUGS


=head1 AUTHOR

Ken Irving <fnkci@uaf.edu> (c) 2008

Licensed under the GPL (Gnu Public Library)

