#!/bin/sh

error () {
    echo "$@" >&2
    exit 1
    }

while test -n "$1"; do
    case "$1" in

        interval=*)
            touch "$1"s
            ;;

        *)
            error unknown argument: $1
    esac
    shift
done

exit

NAME
    TimeSeries.init -- initialize timeseries object

SYNOPSIS
    ob.init [interval=SECONDS]

ATTRIBUTES
    interval=SECONDS
        set an attribute in the timeseries object as given, except
        that 's' will be added as a suffix.

AUTHOR
    (c) ken.irving@alaska.edu 2010

