#!/bin/sh

# try the default case, and then all three forms of the same option...


tob-new --hide --hide-attr foo$$-1

test $(tob foo$$-1.type) = Object:Directory || exit 1
test $(tob foo$$-1.path) = ./.foo$$-1/ || exit 1


tob-new --hide -a foo$$-2

test $(tob foo$$-2.type) = Object:Directory || exit 1
test $(tob foo$$-2.path) = ./.foo$$-2/ || exit 1


rm -r .foo$$-[12]

