#!/usr/bin/perl -w
use strict;
use warnings;

use ThinObject;

my $agg = ThinObject->new( shift );

die unless $agg->isa() ne 'Aggregate';

unless ( @ARGV ) {
    print "$_\n" foreach $agg->get_property( 'order' );
    }
else {
    foreach my $ob ( @ARGV ) {
        die "Aggregate:order error: no contained object $ob\n"
            unless -e $agg->tob() . "/$ob";
        }
    $agg->set_property( 'order', @ARGV );
    }

__END__

=head1 NAME

order -- define order to access contained objects  

=head1 SYNOPSIS

    Aggregate.order object ...

=head1 DESCRIPTION

Creates (overwrites) the order property of the Aggregate object with
the argument values, in order.

=head1 EXAMPLES

    Aggregate.order mine yours theirs

=head1 SEE ALSO

Aggregate.help overview method, Aggregate.do method.

=head1 AUTHOR

Ken Irving <fnkci@uaf.edu> (c) 2007

Licensed under the GPL (Gnu Public Library)

