#!/bin/bash

synopsis="Attr/String.clear"

test -n "$1" && echo synopsis: $synopsis >&2 && exit 1

ln -sf = $TOB_object

exit
    
NAME
    Attr/String.clear -- set string attribute to the empty value

SYNOPSIS
    Attr/String.clear

SEE ALSO
    Attr/String.help

AUTHOR
    ken.irving@alaska.edu (c) 2011

