#!/bin/bash

synopsis="Attr/String.set VALUE..."

ln -sf "=$*" $TOB_object

exit
    
NAME
    Attr/String.set -- set string attribute to given value

SYNOPSIS
    Attr/String.set VALUE ...

AUTHOR
    ken.irving@alaska.edu (c) 2011

