#!/bin/bash

# export TOBLIB=/home/ken/proj/thinobject/src/lib
# export PATH=/home/ken/proj/thinobject/src/bin:$PATH

trap "test -d tmp/$$ && rm -r tmp/$$" EXIT
mkdir tmp$$

cd tmp$$/ || exit

run-parts --regex='[a-z]*-[0-9]+-.*' --exit-on-error --verbose ..
ls ..

cd - >/dev/null
rmdir tmp$$
