#!/bin/bash

synopsis="Attribute/Boolean.show"

if test -n "$boolean_states"; then
    states=(${boolean_states/:/ })
else
    states=(true false)
fi

if test -L $TOB_object; then
    shopt -s nocasematch
    if test "$(readlink $TOB_object)" = "=${states[0]"; then
        echo ${states[0]}
    else
        echo ${states[1]}
    fi
else 
    echo ${states[1]}
fi

exit

NAME
    Attribute/Boolean.show -- print attribute state to standard output

SYNOPSIS
    Attribute/Boolean.show

DESCRIPTION
    True value is displayed if attribute exists and exactly matches the
    true state value, else false value is displayed.  Default states are
    'true' and 'false', or as specified in the boolean_states variable, 
    separated by a colon.

AUTHOR
    ken.irving@alaska.edu (c) 2010

