#!/bin/bash

synopsis="Attr/Integer.set VALUE..."

test -n "$1" || exit 1
int=$1

# echo "RUNNING Attr/Integer.set $int"

test $((int)) = $int || exit 2

test -n "$INT_MIN" && {
    test $INT_MIN -le $int || exit 3
    }

test -n "$INT_MAX" && {
    test $int -le $INT_MAX || exit 4
    }

TOB_resolve_method_path super.set || exit

# echo "RESOLVED super.set as $TOB_method_path"
exec $TOB_method_path $int

# pwd

tob $TOB_object.super.set $int

exit
    
NAME
    Attr/Integer.set -- set Integer attribute to given value

SYNOPSIS
    Attr/Integer.set VALUE ...

AUTHOR
    ken.irving@alaska.edu (c) 2011

