#!/bin/sh

synopsis="Class-Source.init [--git] [-h|--help] class ['as' superclass]"

while :; do
    case $1 in
        --git)
            setup_git=1
            ;;
        -h) exec printf "synopsis: %s\n" "$synopsis"
            ;;
        --help)
            exec awk '/^NAME/{ok=1}ok{print}' $0
            ;;
        -?*)
            printf "synopsis: %s\n" "$synopsis" >&2
            exit 1
            ;;
        *)  break
            ;;
    esac
    shift
done

class=$1 && shift
test -n "$class" || {
    echo missing required class argument >&2
    exec $0 --SHOW-SYNOPSIS-AND-FAIL
    }
    
test "$1" == as && shift &&
    superclass=$1 && shift

test "$superclass" ||
    superclass=Object
    
mkdir lib
test ${class%/*} == $class ||
    mkdir -p ${class%/*}

tob-new lib/$class $superclass
    
test -n "$setup_git" && {
    git init
    git add lib/$class/*
    git add ^ || git add .^
    git commit -am 'initial auto-commit'
    }


exit 0

NAME
    Class-Source.init -- initialize source tree for a thinobject class

DESCRIPTION
    Provide an environment to support development and maintenance of a 
    thinobject class.

METHODS
    


    --help -- Show man page.
    -n  No action. Just report what action would normally occur.
    -s  Silent.
    -t time Pause for time seconds between files (default: $time).
    -v  Verbose."

