#!/bin/bash

synopsis="Boolean.clear"

TOB_resolve_method_path set && 
    exec $TOB_method_path false

exit
    
NAME
    Boolean.clear -- set boolean attribute to false value

SYNOPSIS
    Boolean.clear

ENVIRONMENT VARIABLES
    boolean_states -- colon-separated strings for states, default is true:false
    boolean_remove -- delete attribute file for false state

SEE ALSO
    Boolean.help

AUTHOR
    ken.irving@alaska.edu (c) 2011

