#!/bin/bash

synopsis="Boolean.get"

TOB_resolve_method_path super.get && {
    $TOB_method_path || echo false
    }

exit

NAME
    Boolean.get -- print attribute state to standard output

SYNOPSIS
    Boolean.get

DESCRIPTION
    True value is displayed if attribute exists and exactly matches the
    true state value, else false value is displayed.  Default states are
    'true' and 'false', or as specified in the boolean_states variable, 
    separated by a colon.

AUTHOR
    ken.irving@alaska.edu (c) 2010

