#!/bin/bash

synopsis="Boolean.is true|false"

if test -n "$boolean_states"; then
    states=(${boolean_states/:/ })
else
    states=(true false)
fi

if test -L $TOB_object; then
    state="$(readlink $TOB_object)"
    state="${state#=}"
else
    state="${states[1]}"
fi

if test -n "$1"; then
    assert=$1
elif test -n "$boolean_states"; then
    assert="${boolean_states%:*}"
else
    assert=true
fi

shopt -s nocasematch

test $state = $assert && exit 0

exit 1

NAME
    Boolean.is -- compare state to given argument or true

SYNOPSIS
    Boolean.is [STATE]

AUTHOR
    ken.irving@alaska.edu (c) 2010

