#!/bin/sh

synopsis="Attr/Boolean.is-false"

test -n "$1" && {
    echo "invalid value: $1" >&2
    exit 2
    }

test ! -e $TOB_object

exit

NAME
    Attr/Boolean.is-false -- assert state is false

SYNOPSIS
    Attr/Boolean.is-false

AUTHOR
    ken.irving@alaska.edu (c) 2010

