#!/bin/sh

synopsis="Attr/Boolean.is-true"

test -n "$1" && {
    echo "invalid value: $1" >&2
    exit 2
    }

test -e $TOB_object

exit

NAME
    Attr/Boolean.is-true -- assert state is true

SYNOPSIS
    Attr/Boolean.is-true

AUTHOR
    ken.irving@alaska.edu (c) 2010

