#!/bin/bash

synopsis="Boolean.set [true|false]"
state=true
test -n "$1" && {
    test $1 = true -o $1 = false ||
        error --exit 2 invalid boolean value: $1
    state=$1
    }

TOB_resolve_method_path super.set &&
    exec $TOB_method_path $state

exit
    
NAME
    Boolean.set -- set boolean attribute to true value

SYNOPSIS
    Boolean.set [true|false]

AUTHOR
    ken.irving@alaska.edu (c) 2011

