#!/bin/bash

synopsis="Attribute/Integer.is VALUE"

test "$(readlink $TOB_object)" = "=$(($*))" && exit

exit 1

NAME
    Attribute/Integer.is -- compare attribute value to argument value

SYNOPSIS
    Attribute/Integer.is VALUE

AUTHOR
    ken.irving@alaska.edu (c) 2011

