#!/bin/bash

prefix=/usr/local
host=()

while test -n "$1"; do
    arg=$1 && shift
    case $arg in

    --prefix)
        prefix=$1 && shift
        ;;

    --host)
        host=$1 && shift
        ;;

    -h)
        echo SYNOPSIS install [--prefix PATH] [--host [USER@]HOST] [--help] [-h]
        exit
        ;;

    --help)
        awk '/^NAME/{ok=1}ok{print}' $0
        exit
        ;;

    *)
        echo unknown argument: $arg
        exit 1
        ;;

    esac
done

get_prop () {
    prop=$1
    for path in ${TOB_search_paths//:/ }; do
        test -e $path/$prop && prop=$path/$prop && return
    done
    return 1
    }

get_prop @install-rsync-exclude &&
    opt="--exclude-from=$prop"

# echo TODO: rsync $opt -azv lib/ $host$prefix/lib/tob
# # rsync $opt -azv --delete lib/ $host$prefix/lib/tob
# rsync $opt -azv lib/ $host$prefix/lib/tob

test -n "$host" || host=localhost

echo rsync $opt -azv lib/ $host:$prefix/lib/tob
rsync $opt -azv lib/ $host:$prefix/lib/tob

exit

NAME
    bin/install -- install binaries and libraries for thinobject core system

SYNOPSIS
    bin/install [--prefix PATH] [--host [USER@]HOST] [--help] [-h] 

DESCRIPTION
    Installs or updates an existing installation from the sh, perl,
    and lib directories.

    Binaries are installed in $prefix/bin, thinobject class libraries
    in $prefix/lib/tob, and perl modules in $prefix/lib/site_perl.

    The rsync utility is used to only copy files if newer than existing
    ones.

OPTIONS
    --prefix PATH
    Install path prefix, defaults to /usr/local.
    
    --host HOSTNAME
    --host USER@HOSTNAME
    Any host specifier valid for rsync(1) or ssh(1).  Colon separator is
    appended automatically.  Defaults to "" to install on local host.
    
    -h
    --help
    Short or long help messages.


BUGS
    The --host option is not yet tested, so is disabled.

AUTHOR
    Ken Irving <fnkci@uaf.edu> 2009

