#!/bin/sh

export TOBLIB=/home/ken/proj/thinobject/src/lib
export PATH=/home/ken/proj/thinobject/src/sh:$PATH

mkdir t/tmp$$
cd t/tmp$$/

run-parts --regex='[a-z]*-[0-9]+-.*' --exit-on-error --verbose ..

cd -
rmdir t/tmp$$
