#!/bin/sh

unset SHOW
test -n "$1" && {
    test $1 == --show || {
        echo synopsis: $0 [--show]
        exit 1
        }
    SHOW=--show
    }

cd t ||
    exit 1

for t in t[1-9]*; do
    ./$t $SHOW
done    
