#!/bin/sh

echo SKIPPING $0 && exit

mkdir dir$$ &&
    cd dir$$

ln -s Object ./^

test $(tob ..path) = ./ ||
    exit 2

test $(tob ..type) = Object:Directory ||
    exit 3

cd - >/dev/null

rm -r dir$$

