#!/bin/sh

test -e bad$$ && exit 42
test -e .bad$$ && exit 43

output="$(tob bad$$.path 2>&1)"
code=$?
test $code = 131 && exit
exit $code

## old test code follows:

export TOBLIB_NOT_OBJECT=1
tob bad$$.path 2>/dev/null

test $? = 116 || exit

unset TOBLIB_NOT_OBJECT
tob bad$$.path 2>/dev/null

test $? = 117 || exit

