#!/bin/sh

## in this set of tests I want to check the various options for tob-new

unset SHOW
test -n "$1" && {
    test $1 == --show || {
        echo synopsis: $0 [--show]
        exit 1
        }
    SHOW=1
    }

test "$SHOW" && {
    printf "\n"
    echo $0: test thinobject creation using tob-new and different options:
    }

d=/tmp/tob-test1
ob=test-tob-new

## ensure that the test directory (and hence also any objects) do not exist:
test -d $d &&
    rm -r $d

## create test directory:
mkdir $d &&
    cd $d ||
        exit 1

## arrange to delete test directory on any exit:
trap "rm -r $d" 0 1 2 3 13 15

## create visible object with classlink ^, then with classlink .^
for visibility_option in --no-hide --no-shadow -S; do
    for attr_vis_option in --no-hide-attr -A; do

        test "$SHOW" &&
            echo tob-new $visibility_option $attr_vis_option $ob

        tob-new $visibility_option $attr_vis_option $ob

        # now test that object and class-link attributes are as expected:

        test -d $ob ||
            exit 2

        test -L $ob/^ ||
            exit 3

      # tob-del $ob
        rm -r $ob

        test ! -d $ob ||
            exit 4

    done

    for attr_vis_option in --hide-attr -a; do

        test "$SHOW" &&
            echo tob-new $visibility_option $attr_vis_option $ob

        tob-new $visibility_option $attr_vis_option $ob

        # now test that object and class-link attributes are as expected:

        test -d $ob ||
            exit 5

        test -L $ob/.^ ||
            exit 6

      # tob-del $ob
        rm -r $ob

        test ! -d $ob ||
            exit 7

    done
done
