#!/bin/sh

mkdir dir$$

mkdir dir$$/foo
ln -s Object dir$$/foo/^

mkdir ldir$$

ln -s $PWD/dir$$/foo ldir$$/lfoo

echo NOTE: test has to add extra // to synch with tob

# printf "DEBUG %s\n" "$(tob ldir$$/lfoo.path)" "./ldir$$//lfoo/"

test $(tob ldir$$/lfoo.path) = ./ldir$$//lfoo/ || exit 1

rm -r dir$$ ldir$$
