#!/bin/sh

mkdir dir$$ &&
    cd dir$$

printf "DEBUGGING <<%s>>\n" "$(tob ..path)"
echo SKIPPING ${0##*/} && exit

test "$(tob ..path)" = ./ || exit 2

printf "TEST tob ..type: %s\n" "$(tob ..type)"
test "$(tob ..type)" = Directory || exit 3

cd - >/dev/null
rmdir dir$$
