#!/bin/sh

p=d$$/x/y/z

mkdir -p $p/.foo

ln -s Object $p/.foo/^

## HACK WARNING!
## tob emits some doubled slashes in the path, so just trying
## to accomodate that
q="${p//\////}"

echo NOTE: FIX DOUBLE // IN PATHS FROM tob FOR $0

# printf "DEBUG %s\n" "$(tob $p/foo.path)" "./$q//.foo/" 

test "$(tob $p/foo.path)" = "./$q//.foo/" || exit 2

rm -r d$$

