#!/bin/sh

d=/tmp/tob-test1
test -d $d && {
    echo test directory $d exists, must be manually deleted
    exit 1
    }
mkdir $d &&
    cd $d ||
        exit 2

## arrange to delete test directory on any exit:
trap "rm -r $d" 0 1 2 3 13 15

# create a directory or two:
mkdir foodir .bardir

test "$(tob foodir.path)" == ./foodir || exit 1

test "$(tob bardir.path)" == ./.bardir || exit 1

