#!/bin/sh

echo SKIPPING $0 && exit

ob=ob$$

mkdir .$ob
ln -s Object .$ob/^

mkdir ldir$$

ln -s $PWD/$ob ldir$$/lfoo

printf "DEBUG %s\n" "$(tob ldir$$/lfoo.path)" "$PWD/.$ob/"

test $(tob ldir$$/lfoo.path) = $PWD/.$ob/ || exit 1

rm -r .$ob ldir$$
