#!/bin/sh

echo SKIPPING && exit

test -e bad$$ && exit 42
test -e .bad$$ && exit 43

tob bad$$.path 2>/dev/null
test $? = 1 || exit

exit 2

## old test code follows:

export TOBLIB_NOT_OBJECT=1
tob bad$$.path 2>/dev/null

test $? = 116 || exit

unset TOBLIB_NOT_OBJECT
tob bad$$.path 2>/dev/null

test $? = 117 || exit

