#!/bin/sh

echo SKIPPING $0 && exit

mkdir dir$$

mkdir dir$$/.foo
ln -s Object dir$$/.foo/^

mkdir ldir$$

ln -s ../dir$$/foo ldir$$/lfoo

printf "DEBUG %s\n" "$(tob ldir$$/lfoo.path)" "$PWD/dir$$/.foo/"

test $(tob ldir$$/lfoo.path) = $PWD/dir$$/.foo/ || exit 1

rm -r dir$$ ldir$$
