#!/bin/sh

mkdir dir$$ &&
    cd dir$$

ln -s Directory ^

pwd
ls -l
printf "<<%s>>\n" "$(tob ..path)"

echo A
tob ..path
echo $TOBLIB
echo B

test "$(tob ..path)" = ./ ||
    exit 2

echo 11111111
printf "<<%s>>\n" "$(tob ..type)"
echo 22222222
output=($(tob ..type))
printf "\t<%s>\n" "${output[0]}" "Directory" 
test "${output[0]}" = Directory ||
    exit 3

cd - >/dev/null
rm -r dir$$
