#!/bin/sh

# try the default case, and then all three forms of the same option...

tob-new --hide --no-hide-attr foo$$-1

test $(tob foo$$-1.type) == Object:Directory || exit 1
test $(tob foo$$-1.path) == ./.foo$$-1/ || exit 1


tob-new --hide foo$$-2

test $(tob foo$$-2.type) == Object:Directory || exit 1
test $(tob foo$$-2.path) == ./.foo$$-2/ || exit 1


tob-new -s foo$$-3

test $(tob foo$$-3.type) == Object:Directory || exit 1
test $(tob foo$$-3.path) == ./.foo$$-3/ || exit 1


rm -r .foo$$-[123]

