#!/bin/sh

echo SKIPPING $0 && exit

ob=ob$$

set_symbol() { ln -s "$2" "$1"; }

mkdir .$ob
# ln -s Object .$ob/^
set_symbol .$ob/^ Object || exit
printf "DEBUG <%s>\n" "$(ls -al .$ob)"

# ln -s $ob l$ob
set_symbol l$ob $ob

printf "DEBUG %s\n" "$(tob l$ob.path)" "$PWD/.$ob/"

test $(tob l$ob.path) = $PWD/.$ob/ || exit 1

rm -r .$ob
rm l$ob

