#!/bin/sh

ob=ob$$

mkdir $ob
ln -s Object $ob/^

mkdir ldir$$

ln -s $PWD/$ob ldir$$/lfoo

# printf "DEBUG %s\n" "$(tob ldir$$/lfoo.path)" "./ldir$$//lfoo/"

echo NOTE: test has to add extra // to synch with tob

test $(tob ldir$$/lfoo.path) = ./ldir$$//lfoo/ || exit 1

rm -r $ob ldir$$
