#!/bin/sh

mkdir dir$$ &&
    cd dir$$

ln -s Directory ^

test "$(tob ..path)" = ./ ||
    exit 2

output=($(tob ..type))

# printf "DEBUG <%s>\n" "${output[0]}" "Directory" 

test "${output[0]}" = Directory ||
    exit 3

cd - >/dev/null
rm -r dir$$
