#!/bin/sh

## test whether tob runs with no arguments

output_msg=$(tob 2>&1)
exitcode=$?

test "$exitcode" = 103 || {
    echo unexpected exit code: $exitcode
    exit 1
    }

test "$output_msg" = "no object specified" || {
    echo unexpected output message: $output_msg
    exit 1
    }

