#!/bin/bash

method=$1 && shift
# warn "RUNNING: _default $method"

## ob.method did not resolve, so check for indirect method or attribute type:

## look for type declaration for method
test -L .$method && test ! -e .$method && {
    type=$(readlink $path/$method)
    for lib in ${TOBLIB//:/ }; do
        test -d $lib/$type/ || continue
    done

    }

for path in ${TOB_method_paths//:/ }; do
    test -L $path/$method || continue
    test -e $path/$method && continue
    target=$(readlink $path/$method)

    for toblib in ${TOBLIB//:/ }; do
        test -d $toblib/$target/ || continue
        exec $toblib/$method.default "$@"
    done
    echo failed to resolve $method as indirect method or attribute type >&2
    exit 1
done
    
## no class attribute was resolved, so look for @method or %method properties:

unset property default_handler
for path in ${TOB_search_paths//:/ }; do
    test ! -e $path/$method && test -L $path/$method && { # found symvar?
        property=$path/$method
        default_handler=symvar
        break
        }
    test -e $path/\@$method && { # found @method
        property=$path/@$method
        default_handler=_default-list
        break
        }
    test -e $path/.\@$method && { # found .@method
        property=$path/.@$method
        default_handler=_default-list
        break
        }
    test -e $path/\%$method && { # found %method
        property=$path/%$method
        default_handler=_default-dict
        break
        }
    test -e $path/.\%$method && { # found .%method
        property=$path/.%$method
        default_handler=_default-dict
        break
        }
    test -e $path/\%\@$method && { # found %@method
        property=$path/%@$method
        default_handler=_default-dict-list
        break
        }
    test -e $path/.\%\@$method && { # found .%@method
        property=$path/.%@$method
        default_handler=_default-dict-list
        break
        }
done

test -n "$property" && {
    # search for _default-list or _default-dict method:
    for path in ${TOB_method_paths//:/ }; do
        test -e $path/$default_handler && {
          # echo TODO: /bin/echo exec $path/$default_handler $property $@
            exec $path/$default_handler $property $@ # found & dispatched
            }
    done

    ## ASSERT: property was found, but no default handler, so handle inline:

    test $default_handler == _default-list && { # called ob.foo, found @foo...
        lines="$1"
        test -z "$lines" &&
            exec /bin/cat $property
        exec /usr/bin/perl -e "\$[=1; @r=<>; print @r[$lines]" $property
        # leaving unreachable stub as documentation...
        exec STUB echo $property list accessor lines $lines
        }
    
    test $default_handler == _default-dict && { # called ob.foo, found %foo...
        keys="$@"
        test -z "$keys" &&
            exec /bin/cat $property
        keys=${keys// /|}
        exec /usr/bin/awk -v IGNORECASE=1 "\$1~/$keys/" $property
        exec STUB echo $property dict accessor with keys $keys ${keys// /|}
        }

    test $default_handler == _default-dict-list && { # ... found %@foo...
        keys="$@"
        test -z "$keys" &&
            exec /bin/cat $property
        keys=${keys// /|}
        exec /usr/bin/awk -v IGNORECASE=1 -v keys="$keys" '
            NR==1{
                while(++i<=NF){
                    sub($i,"^" i+1 "$",keys)
                    k[i+1] = $i
                    }
                }
            NR ~ keys {print k[NR]" = "$0}' $property
        exec STUB echo $property dict-list accessor with keys $keys ${keys// /|}
        }
    }

default=${0#*lib/}
default=${default//\//.}
echo $default: method $method not found for object $TOB_object
exit 1
