#!/bin/bash

list=$1; shift
test -e $list || exit 1

show_usage() {
    echo "Object._default-list [--set value] list [lines]"
    exit 0
    }

show_help() {
    cat <<ENDHELP
NAME
  Object._default-list -- thinobject default list property accessor
SYNOPSIS
  _default-list list_property OPTIONS key ...
OPTIONS
  --set -
    pipe standard input into list property
  --set value
    echo value to list property
  -h
    show usage line
  --help
    show help information
AUTHOR
  (c) KIrving fnkci@uaf.edu 30nov2009
ENDHELP
    exit 0
    }

while test "${1:0:1}" == "-"; do # handle option ...
    opt=$1 && shift
    case $opt in
    -h)
        show_usage
        ;;
    --help)
        show_help
        ;;
    --set)
        value=$1 && shift
        ;;
    *)
        echo unknown option: \"$opt\"
        show_usage
        exit 2
        ;;
    esac
done


lines="$1"

test -n "$value" && {
    test -n "$lines" && {
        echo "--set option cannot (yet) be used with lines also specified" 
        exit 1
        }
    if test $value == '-'; then
        exec cat > $list
    else
        exec echo $value > $list
    fi
    }

test -z "$lines" &&
    exec /bin/cat $list
exec /usr/bin/perl -e "\$[=1; @r=<>; print @r[$lines]" $list

