#!/bin/bash

synopsis="File/Symlink/Variable.get"

ob=$TOB_object
test -L $ob || ob=$TOB_class_object
test -L $ob || exit 1

value="$(readlink $ob)"
echo ${value#=}

exit

NAME
    File/Symlink/Variable.get -- print attribute value to standard output

SYNOPSIS
    File/Symlink/Variable.get

AUTHOR
    ken.irving@alaska.edu (c) 2011

