#!/bin/bash

synopsis="File/Symlink/Variable.set VALUE..."

ln -sf "=$*" $TOB_object

exit
    
NAME
    File/Symlink/Variable.set -- set string attribute to given value

SYNOPSIS
    File/Symlink/Variable.set VALUE ...

AUTHOR
    ken.irving@alaska.edu (c) 2011

